name: ProteinTracker
options:
  bundleIdPrefix: com.kimistuff
  deploymentTarget:
    iOS: "17.0"
targets:
  ProteinTracker:
    type: application
    platform: iOS
    sources:
      - path: ProteinTracker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kimistuff.ProteinTracker
        PRODUCT_MODULE_NAME: ProteinTracker
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        SWIFT_VERSION: 5.9
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
  ProteinTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ProteinTrackerTests
    dependencies:
      - target: ProteinTracker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kimistuff.ProteinTrackerTests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.9
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
